export const quotesData = [
    "You are the sunshine in my life.",
    "My love for you is endless.",
    "You complete me.",
    "You make my heart skip a beat.",
    "Forever yours.",
    "世界的温柔，是晚来的善意和干净的你。",
  "长日欣喜，四季予你。",
  "人间有风，有雨，有阳光，还有一个不错的你。",
  "你是我遇见的所有美好里的刚刚好。",
  "平稳而不平淡，快乐而长久。",
  "情不知所起，一往而深。",
  "没有特别的爱好，除了钱就是你。",
  "你好，我是派大星，天上派来爱你的那颗星。",
  "我想给你的爱，是宠溺，是偏爱，是首选。",
  "你是我的今天，明天，和每一天。",
  "岁月变，青春变，你我夫妻心不变，情人节快乐!",
  "情人节快乐，我的爱人。",
  "愿我俩心心相映，白头到老，情人节快乐!",
  "情人节愿与你牵手度过，情人节快乐!",
  "往后余生，万般皆你，情人节快乐!",
  "人生的路很长很长，让我陪你一起走吧，情人节快乐!",
  "情人节到了，爱你没有商量。",
  "比翼双飞一世情，恩爱一生甜蜜笑，情人节快乐!",
  "我是真的，真的，真的爱你，情人节快乐!",
  "你是非常好的人，值得遇到非常好的人，我也如此！",
  "喜欢这东西，就算捂住嘴，也会从眼睛里跑出来。",
  "花会慢慢来，爱你这件事也要慢慢来。",
  "你漫不经心穿梭于我的梦境。",
  "喜欢是一朝一夕，爱是从心动到古稀。",
  "自从遇见可爱的你，生活一下子都变天了。",
  "所有可以分享的美好瞬间第一个想到的都是你。",
  "永远做公主，梦都陪你一一实现。",
  "我以为我只是心动一下，没想到心动是一春又一夏天，一夏又一冬…",
  "所有人都漂浮在天上，只有你沉在我心里。",
  "我用了整个冬天，把喜欢你这件事死死的焊在了眼睛里，于是现在我的满眼皆是你。",
  "没见面的日子，每一片花瓣代表着一个想念。",
  "夏天是你，而你比夏天更美好；春天是你，而你又比春天更美好……",
  "给大家介绍一下，这是我的手机屏保，微信头像，朋友圈背景，聊天背景，还是我可以向全世界炫耀住进我心房那个人…",
  "与其说你美好，不如说你不可重复。",
  "有时候我词不达意，但我真的很高兴遇见你。",
  "想请你到我怀里坐一坐。",
  "喜欢你，乍见心欢，小别思念，久处仍怦然心动。",
  "你闯进我的镜头，我按下了永远。",
  "这世上所有温柔的事情，都让我想起你。",
  "最幸福的事，就是在喜欢你的每一天里，被你喜欢。",
  "现在是现在，以后是以后，时间过得再长，我也不会忘记我们的现在。",
  "我愿化身为一叶小舟，驶向你的心海。",
  "思念，就是我的心在呼唤你的名字。",
  "你是我的信仰，让我在黑暗中看到光明。",
  "我的世界因你而精彩，我的心因你而快乐。",
  "你是我生命中最美丽的意外。",
  "和你在一起的每一天都是情人节。",
  "你是我不期而遇的幸福。",
  "每天醒来都觉得很幸福，因为有你。",
  "你是我心中永远的那颗星。",
  "有你的日子是最好的日子。",
  "你是我生命中的一道阳光，永远照耀着我的心灵。",
  "因为有了你，我的世界变得更加美好。",
  "在茫茫人海中，我遇到了你，我觉得很幸运。",
  "你是我的梦中情人，也是我的现实爱人。",
  "你是我心中的英雄，我的白马王子。",
  "你的微笑是我最大的幸福。",
  "你的一举一动都让我感到无比幸福。",
  "你的笑容是我每天最期待的事情。",
  "你是我一生中最重要的人。",
  "有你的日子是最美的日子。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day.",
  "On Valentine's Day and every day, love the one you're with.",
  "A flower cannot blossom without sunshine, and a man cannot live without love. - Max Muller",
  "Love is the greatest refreshment in life. - Pablo Picasso",
  "The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart. - Helen Keller",
  "Love doesn't make the world go 'round. Love is what makes the ride worthwhile. - Franklin P. Jones",
  "In true love, the smallest distance is too great, and the greatest distance can be bridged. - Hans Nouwens",
  "A true love story never ends.",
  "The best thing to hold onto in life is each other. - Audrey Hepburn",
  "Love is not just looking at each other; it's looking in the same direction. - Antoine de Saint-Exupéry",
  "Love is when the other person's happiness is more important than your own. - H. Jackson Brown, Jr.",
  "Your flaws are perfect for the heart that's meant to love you.",
  "Love is the only gold. - Alfred Lord Tennyson",
  "Being deeply loved by someone gives you strength while loving someone deeply gives you courage. - Lao Tzu",
  "Love is like the wind, you can't see it but you can feel it. - Nicholas Sparks",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "你是我心灵的归宿，是我生命的全部。",
  "你是我心中的唯一。",
  "你是我生命中最重要的人。",
  "有了你，我的世界变得更加美好。",
  "Love is an endless mystery, for it has nothing else to explain it. - Rabindranath Tagore",
  "Love is composed of a single soul inhabiting two bodies. - Aristotle",
  "True love stories never have endings. - Richard Bach",
  "Love is the poetry of the senses. - Honoré de Balzac",
  "Love is the greatest gift when given. It is the highest honor when received. - Fawn Weaver",
  "The best thing to hold onto in life is each other. - Audrey Hepburn",
  "Love is like a beautiful flower which I may not touch, but whose fragrance makes the garden a place of delight just the same. - Helen Keller",
  "Gravitation is not responsible for people falling in love. - Albert Einstein",
  "Love is a canvas furnished by nature and embroidered by imagination. - Voltaire",
  "Love is something eternal; the aspect may change, but not the essence. - Vincent van Gogh",
  "Love is a game that two can play and both win. - Eva Gabor",
  "The art of love is largely the art of persistence. - Albert Ellis",
  "There is only one happiness in life: to love and be loved. - George Sand",
  "Love is the only force capable of transforming an enemy into a friend. - Martin Luther King, Jr.",
  "The heart has its reasons of which reason knows nothing. - Blaise Pascal"
  ];